###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password123"
}

###
POST http://localhost:5000/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMmNkMzE1OC1jMDcwLTRlYmItYmU4NS00ZWI3ZDUwNTcwODkiLCJpYXQiOjE3NzA4MzA3NDMsImV4cCI6MTc3MTQzNTU0M30.YrHA6lVKlc4u3sDfy-GaRL0upujRCBomFXgegZUunIA"
}
